services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

    restart: always
    volumes:
      - mongo-db:/data/db

    networks:
      - mern-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: baburhat-backend

    container_name: backend
    working_dir: /app
    ports:
      - 5000:5000
      - 35729:35729

    restart: always
    volumes:
      - .:/app

    environment:
      MONGO_HOST: mongodb:27017
    
    depends_on:
      - mongodb
    
    networks:
      - mern-network


volumes:
  mongo-db:

networks:
  mern-network: 
